### ISSUE TITLE
ListBox module shows JSON object instead of text value

### ISSUE THREAD

**Issue by Mjrtoo** [MatKlucznyk/Qsys#23]
When I use the ListBox named control for a selector component, selection box, it displays the JSON object on the XSIG output rather than just the "Text":"" of the JSON.
![listbox](https://github.com/MatKlucznyk/Qsys/assets/34356905/38836abf-c80e-4a64-8221-606051990ce8)

**Comment by MatKlucznyk** [comment]
The combo box and list box both support various values. These can be anything from a string to an array. Since the value cannot be determined you will have to parse the value outside of this library to suit the needs of the value.

That being said, I am considering adding the selector control as a named component module since the value in the selection combo box is determinable.

Marking this as closed for now.
