### ISSUE TITLE
Meters

### ISSUE THREAD

**Issue by muzicman82** [MatKlucznyk/Qsys#35]
Is there the ability or need to enable/disable meters? With other modules/DSPs, I typically only enable a meter module when that meter is displayed on a GUI. 

I'm showing 8-10 meters on a GUI page. I've done this many times before with the old v5.2 modules so I don't suspect any issue with your set, but should I be concerned about the extra traffic?

**Comment by MatKlucznyk** [comment]
The update from QSYS is set at 300ms so the processor would not get updates any faster or slower. The data payload would be slightly larger consistently than normal with 8-10 meters but shouldn't cause any bottle necks.

That being said, the meter modules are not 100% accurate because QSYS is sampling them at 300ms.

**Comment by muzicman82** [comment]
This is good info, thanks.
